Packages

In [13]:
from pathlib import Path
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

Paths to Result Summaries

In [14]:
summary_fed_path = Path("/Users/lorenzouberti/Desktop/BANQUE DE FRANCE /Github Repos/Project/BdF-Project/Extension LLM Classification Task/Fed Side/Results")
summary_ecb_path = Path("/Users/lorenzouberti/Desktop/BANQUE DE FRANCE /Github Repos/Project/BdF-Project/Extension LLM Classification Task/ECB Side/results")
# Summary FED. 
summary_fed_statements_pressconf = pd.read_csv(summary_fed_path / "summary__fed_statements_presconf.csv")
summary_fed_speeches = pd.read_csv(summary_fed_path / "summary__fed_speeches.csv" )
# Summary ECB
summary_ecb_statements_pressconf = pd.read_csv(summary_ecb_path / "summary__ECB_statements_presconf.csv")
summary_ecb_speeches = pd.read_csv(summary_ecb_path / "summary__ECB_speeches.csv")

In [15]:
summary_ecb_statements_pressconf.head(20)

,model,prompt,n,parsed,errors,accuracy,macro_f1,in_tok,out_tok,cost_usd
0,claude-haiku,p1_analyst_direct,2044,2043,0,0.720,0.701,525434,10220,0.577
1,claude-haiku,p2_analyst_rubric,2044,2043,0,0.696,0.683,917882,10220,0.969
2,claude-haiku,p3_analyst_rules,2044,2043,0,0.664,0.622,576534,143327,1.293
3,claude-haiku,p4_analyst_json,2044,2043,0,0.699,0.663,410970,23676,0.529
4,claude-haiku,p5_analyst_fewshot,2044,2043,0,0.690,0.677,619458,10220,0.671
5,claude-sonnet,p1_analyst_direct,2044,2043,0,0.701,0.685,527478,10369,1.738
6,claude-sonnet,p2_analyst_rubric,2044,2043,0,0.691,0.667,919926,10220,2.913
7,claude-sonnet,p3_analyst_rules,2044,2043,0,0.680,0.655,578578,36703,2.286
8,claude-sonnet,p4_analyst_json,2044,2043,0,0.720,0.707,413014,18396,1.515
9,claude-sonnet,p5_analyst_fewshot,2044,2043,0,0.677,0.660,621502,10220,2.018
10,deepseek-chat,p1_analyst_direct,2044,2043,0,0.672,0.651,469666,2044,0.132
11,deepseek-chat,p2_analyst_rubric,2044,2043,0,0.611,0.573,798750,2044,0.225
12,deepseek-chat,p3_analyst_rules,2044,2043,0,0.652,0.619,528942,2044,0.149
13,deepseek-chat,p4_analyst_json,2044,2043,0,0.701,0.678,371554,12264,0.109
14,deepseek-chat,p5_analyst_fewshot,2044,2043,0,0.601,0.596,569822,2044,0.160
15,deepseek-reasoner,p1_analyst_direct,2044,2043,0,0.717,0.702,631142,275740,0.292
16,deepseek-reasoner,p2_analyst_rubric,2044,2040,0,0.718,0.701,960226,391033,0.433
17,deepseek-reasoner,p3_analyst_rules,2044,2041,0,0.706,0.681,690418,338296,0.335
18,deepseek-reasoner,p4_analyst_json,2044,2043,0,0.736,0.719,533030,336224,0.290
19,deepseek-reasoner,p5_analyst_fewshot,2044,2043,0,0.712,0.690,731298,248607,0.309

In [16]:
print(summary_ecb_statements_pressconf.columns)

Index(['model', 'prompt', 'n', 'parsed', 'errors', 'accuracy', 'macro_f1',
       'in_tok', 'out_tok', 'cost_usd'],
      dtype='str')

In [17]:
summary_ecb_speeches.head(2)

,model,prompt,n,parsed,errors,accuracy,macro_f1,in_tok,out_tok,cost_usd
0,claude-haiku,p1_analyst_direct,1000,1000,0,0.683,0.684,256644,5000,0.282
1,claude-haiku,p2_analyst_rubric,1000,1000,0,0.649,0.652,448644,5000,0.474

In [18]:
# ============================================================
# FED vs ECB — model × prompt comparison on macro-F1
# Paste below your loading cell (uses your existing variables).
# ============================================================
import numpy as np
import pandas as pd

try:
    display  # available in notebooks
except NameError:
    display = print

pd.set_option("display.float_format", lambda v: f"{v:.3f}")

runs = pd.concat(
    [
        summary_fed_statements_pressconf.assign(bank="FED", doc_type="statements_pressconf"),
        summary_fed_speeches.assign(bank="FED", doc_type="speeches"),
        summary_ecb_statements_pressconf.assign(bank="ECB", doc_type="statements_pressconf"),
        summary_ecb_speeches.assign(bank="ECB", doc_type="speeches"),
    ],
    ignore_index=True,
)
runs["dataset"] = runs["bank"] + "_" + runs["doc_type"]

# ------------------------------------------------------------
# A · Raw picture — mean macro-F1 per model, per bank
#     (averaged over the 5 prompts and both doc types)
#     NB: ECB_minus_FED here mixes model skill with dataset
#     difficulty — table C fixes that.
# ------------------------------------------------------------
model_by_bank = (
    runs.pivot_table(index="model", columns="bank", values="macro_f1", aggfunc="mean")
        .assign(ECB_minus_FED=lambda d: d["ECB"] - d["FED"])
        .sort_values("ECB_minus_FED", ascending=False)
)
print("A · mean macro-F1 per model × bank")
display(model_by_bank)

# finer grain: one column per dataset
model_by_dataset = runs.pivot_table(
    index="model", columns="dataset", values="macro_f1", aggfunc="mean"
)
print("A2 · mean macro-F1 per model × dataset")
display(model_by_dataset)

# ------------------------------------------------------------
# B · Prompt lift — your idea:
#     each run minus that model's OWN average on the same
#     dataset. Positive = this prompt pushes the model above
#     its usual level; comparable across models because each
#     model is measured against itself.
# ------------------------------------------------------------
runs["prompt_lift"] = runs["macro_f1"] - runs.groupby(["dataset", "model"])[
    "macro_f1"
].transform("mean")

prompt_lift_by_bank = runs.pivot_table(
    index="prompt", columns="bank", values="prompt_lift", aggfunc="mean"
)
print("B · average prompt lift, net of model strength")
display(prompt_lift_by_bank)

# per-model detail (heatmap-ready): which prompt works for WHICH model
prompt_lift_detail = runs.pivot_table(
    index="model", columns=["bank", "prompt"], values="prompt_lift", aggfunc="mean"
)
print("B2 · prompt lift per model (columns: bank × prompt)")
display(prompt_lift_detail)

# ------------------------------------------------------------
# C · Relative model skill — the same centring trick, flipped:
#     each run minus the DATASET average over all models and
#     prompts. This removes dataset difficulty, so
#     ECB_minus_FED > 0 really means "relatively stronger on
#     ECB than the field", not "ECB was easier".
# ------------------------------------------------------------
runs["rel_skill"] = runs["macro_f1"] - runs.groupby("dataset")["macro_f1"].transform("mean")

rel_skill_by_bank = (
    runs.pivot_table(index="model", columns="bank", values="rel_skill", aggfunc="mean")
        .assign(ECB_minus_FED=lambda d: d["ECB"] - d["FED"])
        .sort_values("ECB_minus_FED", ascending=False)
)
print("C · relative skill (dataset-demeaned macro-F1)")
display(rel_skill_by_bank)

# ------------------------------------------------------------
# Extra · best prompt per model & bank (on average macro-F1)
# ------------------------------------------------------------
mp = runs.groupby(["bank", "model", "prompt"], as_index=False)["macro_f1"].mean()
best_prompt = (
    mp.loc[mp.groupby(["bank", "model"])["macro_f1"].idxmax()]
      .sort_values(["bank", "macro_f1"], ascending=[True, False])
      .reset_index(drop=True)
)
print("Best prompt per model × bank")
display(best_prompt)

# ============================================================
# FED vs ECB — D · median robustness, E · document weighting,
#              F · sanity checks implied by the construction
# Paste below the comparison cell. Requires from that cell:
#   runs   (with columns prompt_lift and rel_skill already added)
#   model_by_bank, prompt_lift_by_bank, rel_skill_by_bank
# ============================================================
import numpy as np
import pandas as pd

try:
    display  # available in notebooks
except NameError:
    display = print

# ------------------------------------------------------------
# D · Robustness — medians instead of means
#     One catastrophic run (e.g. JSON parsing failure) drags a
#     10-run mean by drop/10 but barely moves the median
#     (breakdown point ≈ 50% vs 0% for the mean). If the
#     rankings below match tables A and C, the mean results are
#     not outlier-driven.
# ------------------------------------------------------------

# D1 · table A re-run with aggfunc="median"
model_by_bank_median = (
    runs.pivot_table(index="model", columns="bank", values="macro_f1", aggfunc="median")
        .assign(ECB_minus_FED=lambda d: d["ECB"] - d["FED"])
        .sort_values("ECB_minus_FED", ascending=False)
)
print("D1 · median macro-F1 per model × bank")
display(model_by_bank_median)

# D2 · table C re-run with aggfunc="median"
#      (mean-demeaned rel_skill, median-aggregated — the literal
#       re-run suggested in the notes)
rel_skill_by_bank_median = (
    runs.pivot_table(index="model", columns="bank", values="rel_skill", aggfunc="median")
        .assign(ECB_minus_FED=lambda d: d["ECB"] - d["FED"])
        .sort_values("ECB_minus_FED", ascending=False)
)
print("D2 · median relative skill per model × bank")
display(rel_skill_by_bank_median)

# D2b · fully robust alternative: demean by the DATASET MEDIAN,
#       then aggregate by median, so no mean enters anywhere.
runs["rel_skill_med"] = runs["macro_f1"] - runs.groupby("dataset")["macro_f1"].transform("median")
rel_skill_med_by_bank = (
    runs.pivot_table(index="model", columns="bank", values="rel_skill_med", aggfunc="median")
        .assign(ECB_minus_FED=lambda d: d["ECB"] - d["FED"])
        .sort_values("ECB_minus_FED", ascending=False)
)
print("D2b · fully median-based relative skill (median-demeaned, median-aggregated)")
display(rel_skill_med_by_bank)

# D3 · is the model ranking stable under mean vs median?
#      Spearman rho computed as Pearson on ranks (no scipy needed).
stability = pd.DataFrame({
    "gap_mean": model_by_bank["ECB_minus_FED"],
    "gap_median": model_by_bank_median["ECB_minus_FED"],
})
stability["rank_mean"] = stability["gap_mean"].rank(ascending=False, method="min").astype(int)
stability["rank_median"] = stability["gap_median"].rank(ascending=False, method="min").astype(int)
spearman_rho = stability["gap_mean"].rank().corr(stability["gap_median"].rank())
print("D3 · rank stability of ECB_minus_FED (1 = most ECB-leaning)")
display(stability.sort_values("rank_mean"))
print(f"Spearman rho (mean vs median ranking) = {spearman_rho:.3f}")

# D4 · screen for tanked runs — inspect these raw outputs before
#      trusting any mean-based table.
TANK_THRESHOLD = -0.05  # macro-F1 points below the model's own (model, dataset) mean; adjust
tanked = (
    runs.loc[runs["prompt_lift"] < TANK_THRESHOLD,
             ["model", "dataset", "prompt", "macro_f1", "prompt_lift"]]
        .sort_values("prompt_lift")
)
print(f"D4 · runs more than {-TANK_THRESHOLD:.2f} below their own (model, dataset) mean: {len(tanked)}")
display(tanked)

# ------------------------------------------------------------
# E · Document-weighted aggregation
#     Equal-weight means treat each corpus as one task; document
#     weighting treats each document equally, so statements
#     (~2044 docs) count ≈2× speeches (~1000). n varies only at
#     the dataset level, so the demeaning behind rel_skill is
#     UNCHANGED — only the cross-doc-type aggregation reweights.
#     NB: a document-weighted average of per-corpus macro-F1 is
#     NOT the macro-F1 of the pooled corpus (F1 is a ratio metric
#     and does not decompose across corpora). Report it as a
#     weighted average of per-corpus scores.
# ------------------------------------------------------------

if "n" not in runs.columns:
    # TODO: replace with your true document counts per (bank, doc_type)
    n_docs = {
        ("FED", "statements_pressconf"): 2044,
        ("FED", "speeches"): 1000,
        ("ECB", "statements_pressconf"): 2044,
        ("ECB", "speeches"): 1000,
    }
    runs["n"] = [n_docs[(b, t)] for b, t in zip(runs["bank"], runs["doc_type"])]


def weighted_by_bank(df, value_col):
    """n-weighted mean of value_col per model × bank.

    Sum-of-products form: avoids groupby.apply, so it is stable
    across pandas versions and raises no deprecation warnings.
    """
    tmp = df.assign(_wx=df[value_col] * df["n"])
    g = tmp.groupby(["model", "bank"])[["_wx", "n"]].sum()
    return (g["_wx"] / g["n"]).unstack("bank")


# E1 · document-weighted table A
model_by_bank_weighted = (
    weighted_by_bank(runs, "macro_f1")
    .assign(ECB_minus_FED=lambda d: d["ECB"] - d["FED"])
    .sort_values("ECB_minus_FED", ascending=False)
)
print("E1 · document-weighted mean macro-F1 per model × bank")
display(model_by_bank_weighted)

# E2 · document-weighted table C
rel_skill_by_bank_weighted = (
    weighted_by_bank(runs, "rel_skill")
    .assign(ECB_minus_FED=lambda d: d["ECB"] - d["FED"])
    .sort_values("ECB_minus_FED", ascending=False)
)
print("E2 · document-weighted relative skill")
display(rel_skill_by_bank_weighted)

# E3 · document-weighted best prompt per model × bank
mp_w = (
    runs.assign(_wx=runs["macro_f1"] * runs["n"])
        .groupby(["bank", "model", "prompt"], as_index=False)[["_wx", "n"]].sum()
        .assign(macro_f1_w=lambda d: d["_wx"] / d["n"])
)
best_prompt_weighted = (
    mp_w.loc[mp_w.groupby(["bank", "model"])["macro_f1_w"].idxmax(),
             ["bank", "model", "prompt", "macro_f1_w"]]
        .sort_values(["bank", "macro_f1_w"], ascending=[True, False])
        .reset_index(drop=True)
)
print("E3 · document-weighted best prompt per model × bank")
display(best_prompt_weighted)

# ------------------------------------------------------------
# F · Numerical sanity checks implied by the construction
#     Within-cell sums are identically zero however many runs
#     exist; the bank-level column sums are exactly zero only on
#     a complete model × prompt × dataset grid.
# ------------------------------------------------------------
assert np.allclose(runs.groupby(["dataset", "model"])["prompt_lift"].sum(), 0, atol=1e-9), \
    "prompt_lift must sum to 0 within every (dataset, model) cell"
assert np.allclose(runs.groupby("dataset")["rel_skill"].sum(), 0, atol=1e-9), \
    "rel_skill must sum to 0 within every dataset"

print("F · column sums (≈ 0 by construction on a complete grid):")
print("    B, lift per bank:      ", prompt_lift_by_bank.sum().round(6).to_dict())
print("    C, rel. skill per bank:", rel_skill_by_bank[["FED", "ECB"]].sum().round(6).to_dict())

A · mean macro-F1 per model × bank

bank                ECB   FED  ECB_minus_FED
model
deepseek-reasoner 0.706 0.653          0.053
mistral-large     0.668 0.624          0.044
deepseek-chat     0.593 0.550          0.044
claude-sonnet     0.677 0.635          0.042
claude-haiku      0.660 0.629          0.031
gpt-5.1           0.665 0.646          0.019
mistral-small     0.610 0.595          0.015
gpt-5-mini        0.634 0.635         -0.001

A2 · mean macro-F1 per model × dataset

dataset,ECB_speeches,ECB_statements_pressconf,FED_speeches,FED_statements_pressconf
model,,,,
claude-haiku,0.651,0.669,0.623,0.636
claude-sonnet,0.678,0.675,0.660,0.610
deepseek-chat,0.563,0.623,0.561,0.538
deepseek-reasoner,0.713,0.699,0.665,0.641
gpt-5-mini,0.604,0.663,0.630,0.640
gpt-5.1,0.636,0.695,0.648,0.644
mistral-large,0.655,0.681,0.627,0.620
mistral-small,0.600,0.619,0.593,0.596

B · average prompt lift, net of model strength

bank                  ECB    FED
prompt
p1_analyst_direct   0.018  0.023
p2_analyst_rubric  -0.032 -0.014
p3_analyst_rules   -0.011  0.009
p4_analyst_json     0.032  0.007
p5_analyst_fewshot -0.006 -0.025

B2 · prompt lift per model (columns: bank × prompt)

bank                            ECB                                     \
prompt            p1_analyst_direct p2_analyst_rubric p3_analyst_rules
model
claude-haiku                  0.032             0.007           -0.048
claude-sonnet                 0.017            -0.012           -0.017
deepseek-chat                 0.035            -0.064            0.013
deepseek-reasoner            -0.014            -0.007           -0.013
gpt-5-mini                    0.033            -0.054           -0.001
gpt-5.1                       0.011            -0.045           -0.000
mistral-large                 0.013            -0.015           -0.010
mistral-small                 0.013            -0.068           -0.016

bank                                                               FED  \
prompt            p4_analyst_json p5_analyst_fewshot p1_analyst_direct
model
claude-haiku               -0.005              0.014             0.024
claude-sonnet               0.025             -0.013             0.020
deepseek-chat               0.077             -0.061             0.077
deepseek-reasoner           0.024              0.010             0.019
gpt-5-mini                  0.033             -0.011             0.023
gpt-5.1                     0.037             -0.003             0.017
mistral-large               0.027             -0.015             0.001
mistral-small               0.041              0.029             0.001

bank                                                                  \
prompt            p2_analyst_rubric p3_analyst_rules p4_analyst_json
model
claude-haiku                  0.030           -0.006          -0.037
claude-sonnet                 0.017           -0.022           0.013
deepseek-chat                -0.166            0.058           0.074
deepseek-reasoner             0.023           -0.007          -0.006
gpt-5-mini                    0.006            0.010           0.004
gpt-5.1                      -0.008            0.016          -0.000
mistral-large                 0.007            0.013          -0.000
mistral-small                -0.022            0.012           0.009

bank
prompt            p5_analyst_fewshot
model
claude-haiku                  -0.010
claude-sonnet                 -0.029
deepseek-chat                 -0.044
deepseek-reasoner             -0.029
gpt-5-mini                    -0.044
gpt-5.1                       -0.025
mistral-large                 -0.021
mistral-small                 -0.001

C · relative skill (dataset-demeaned macro-F1)

bank                 ECB    FED  ECB_minus_FED
model
deepseek-reasoner  0.054  0.032          0.022
mistral-large      0.017  0.003          0.014
deepseek-chat     -0.058 -0.071          0.013
claude-sonnet      0.025  0.014          0.011
claude-haiku       0.009  0.009          0.000
gpt-5.1            0.014  0.025         -0.012
mistral-small     -0.042 -0.026         -0.016
gpt-5-mini        -0.018  0.014         -0.032

Best prompt per model × bank

   bank              model             prompt  macro_f1
0   ECB  deepseek-reasoner    p4_analyst_json     0.730
1   ECB            gpt-5.1    p4_analyst_json     0.702
2   ECB      claude-sonnet    p4_analyst_json     0.702
3   ECB      mistral-large    p4_analyst_json     0.695
4   ECB       claude-haiku  p1_analyst_direct     0.692
5   ECB      deepseek-chat    p4_analyst_json     0.671
6   ECB         gpt-5-mini  p1_analyst_direct     0.667
7   ECB      mistral-small    p4_analyst_json     0.650
8   FED  deepseek-reasoner  p2_analyst_rubric     0.676
9   FED            gpt-5.1  p1_analyst_direct     0.663
10  FED       claude-haiku  p2_analyst_rubric     0.659
11  FED         gpt-5-mini  p1_analyst_direct     0.658
12  FED      claude-sonnet  p1_analyst_direct     0.655
13  FED      mistral-large   p3_analyst_rules     0.636
14  FED      deepseek-chat  p1_analyst_direct     0.627
15  FED      mistral-small   p3_analyst_rules     0.607

D1 · median macro-F1 per model × bank

bank                ECB   FED  ECB_minus_FED
model
deepseek-reasoner 0.702 0.647          0.054
mistral-large     0.676 0.627          0.049
claude-haiku      0.667 0.633          0.034
gpt-5.1           0.676 0.647          0.029
claude-sonnet     0.667 0.645          0.022
mistral-small     0.612 0.595          0.017
gpt-5-mini        0.640 0.639          0.001
deepseek-chat     0.600 0.605         -0.005

D2 · median relative skill per model × bank

bank                 ECB    FED  ECB_minus_FED
model
deepseek-reasoner  0.049  0.030          0.019
mistral-large      0.012  0.005          0.006
claude-haiku       0.013  0.013          0.000
claude-sonnet      0.025  0.030         -0.005
mistral-small     -0.040 -0.026         -0.014
gpt-5.1            0.013  0.027         -0.014
gpt-5-mini        -0.011  0.016         -0.027
deepseek-chat     -0.045 -0.013         -0.032

D2b · fully median-based relative skill (median-demeaned, median-aggregated)

bank                 ECB    FED  ECB_minus_FED
model
deepseek-reasoner  0.040  0.018          0.022
mistral-large      0.001 -0.004          0.005
claude-haiku       0.004  0.002          0.002
claude-sonnet      0.019  0.018          0.001
mistral-small     -0.048 -0.036         -0.011
gpt-5.1            0.004  0.016         -0.012
gpt-5-mini        -0.023  0.005         -0.028
deepseek-chat     -0.054 -0.023         -0.031

D3 · rank stability of ECB_minus_FED (1 = most ECB-leaning)

                   gap_mean  gap_median  rank_mean  rank_median
model
deepseek-reasoner     0.053       0.054          1            1
mistral-large         0.044       0.049          2            2
deepseek-chat         0.044      -0.005          3            8
claude-sonnet         0.042       0.022          4            5
claude-haiku          0.031       0.034          5            3
gpt-5.1               0.019       0.029          6            4
mistral-small         0.015       0.017          7            6
gpt-5-mini           -0.001       0.001          8            7

Spearman rho (mean vs median ranking) = 0.571
D4 · runs more than 0.05 below their own (model, dataset) mean: 11

,model,dataset,prompt,macro_f1,prompt_lift
51,deepseek-chat,FED_speeches,p2_analyst_rubric,0.387,-0.174
11,deepseek-chat,FED_statements_pressconf,p2_analyst_rubric,0.381,-0.157
134,deepseek-chat,ECB_speeches,p5_analyst_fewshot,0.469,-0.095
116,mistral-small,ECB_statements_pressconf,p2_analyst_rubric,0.528,-0.091
131,deepseek-chat,ECB_speeches,p2_analyst_rubric,0.486,-0.078
14,deepseek-chat,FED_statements_pressconf,p5_analyst_fewshot,0.469,-0.069
146,gpt-5.1,ECB_speeches,p2_analyst_rubric,0.571,-0.065
141,gpt-5-mini,ECB_speeches,p2_analyst_rubric,0.540,-0.065
24,gpt-5-mini,FED_statements_pressconf,p5_analyst_fewshot,0.583,-0.057
43,claude-haiku,FED_speeches,p4_analyst_json,0.569,-0.054
91,deepseek-chat,ECB_statements_pressconf,p2_analyst_rubric,0.573,-0.050

E1 · document-weighted mean macro-F1 per model × bank

bank                ECB   FED  ECB_minus_FED
model
deepseek-chat     0.604 0.546          0.058
deepseek-reasoner 0.704 0.649          0.055
claude-sonnet     0.676 0.623          0.053
mistral-large     0.673 0.622          0.050
claude-haiku      0.663 0.632          0.032
gpt-5.1           0.675 0.645          0.030
mistral-small     0.613 0.595          0.018
gpt-5-mini        0.644 0.636          0.007

E2 · document-weighted relative skill

bank                 ECB    FED  ECB_minus_FED
model
deepseek-chat     -0.053 -0.073          0.021
deepseek-reasoner  0.047  0.030          0.017
claude-sonnet      0.020  0.004          0.015
mistral-large      0.016  0.004          0.013
claude-haiku       0.007  0.013         -0.006
gpt-5.1            0.019  0.026         -0.007
mistral-small     -0.044 -0.024         -0.020
gpt-5-mini        -0.013  0.018         -0.030

E3 · document-weighted best prompt per model × bank

   bank              model             prompt  macro_f1_w
0   ECB  deepseek-reasoner    p4_analyst_json       0.726
1   ECB            gpt-5.1    p4_analyst_json       0.709
2   ECB      claude-sonnet    p4_analyst_json       0.703
3   ECB      mistral-large    p4_analyst_json       0.697
4   ECB       claude-haiku  p1_analyst_direct       0.695
5   ECB         gpt-5-mini  p1_analyst_direct       0.678
6   ECB      deepseek-chat    p4_analyst_json       0.673
7   ECB      mistral-small    p4_analyst_json       0.665
8   FED  deepseek-reasoner  p2_analyst_rubric       0.669
9   FED         gpt-5-mini  p1_analyst_direct       0.665
10  FED       claude-haiku  p2_analyst_rubric       0.663
11  FED            gpt-5.1   p3_analyst_rules       0.661
12  FED      claude-sonnet  p1_analyst_direct       0.651
13  FED      mistral-large  p2_analyst_rubric       0.638
14  FED      deepseek-chat  p1_analyst_direct       0.628
15  FED      mistral-small   p3_analyst_rules       0.612

F · column sums (≈ 0 by construction on a complete grid):
    B, lift per bank:       {'ECB': -0.0, 'FED': -0.0}
    C, rel. skill per bank: {'FED': -0.0, 'ECB': 0.0}